[settings]
auto_install = false

[tasks.hot]
description = "Run with hot reload"
dir = "."
run = "dx serve --features dev"

[tasks.dev]
dir = "."
run = "cargo run --features dev"

[tasks.release]
dir = "."
run = "cargo build --profile small --features desktop"

[tasks.dev-tool]
dir = "."
run = "freya-devtools-app"

[tasks.dev-ui]
depends = ["dev", "dev-tool"]